OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Controllers/CategoryController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShoppingWebApplication.Service.Services;
using OnlineShoppingWebApplication.Service.Services.DTOs;
using OnlineShoppingWebApplication.ViewModels.Paging.Category;
using System;
using System.Threading.Tasks;

namespace OnlineShoppingWebApplication.WebApp.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly INotyfService _notyfService;
        public CategoryController(ICategoryService categoryService, INotyfService notyfService)
        {
            _categoryService = categoryService;
            _notyfService = notyfService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 3)
        {
            GetCategoryPagingRequest request = new GetCategoryPagingRequest()
            {
                Keyword = keyword,
                PageSize = pageSize,
                PageIndex = pageIndex
            };

            ViewBag.Keyword = request.Keyword;

            var categories = await _categoryService.GetCategoriesPaging(request);
            return View(categories.ResultObj);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = await _categoryService.Create(dto);
            if (result.IsSuccessed)
            {
                _notyfService.Success(result.Message);
                return RedirectToAction("Index");
            }

            _notyfService.Error(result.Message);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var category = await _categoryService.GetById(id);
            if (category.IsSuccessed)
            {
                return View(category.ResultObj);
            }

            _notyfService.Error(category.Message);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            var category = await _categoryService.Edit(dto);
            if (category.IsSuccessed)
            {
                _notyfService.Success(category.Message);
                return RedirectToAction("Index");
            }

            _notyfService.Error(category.Message);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _categoryService.DeleteById(id);
            if (result.IsSuccessed)
            {
                _notyfService.Success(result.Message);
            }
            else
            {
                _notyfService.Error(result.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var category = await _categoryService.GetById(id);
            if (category.IsSuccessed)
            {
                return View(category.ResultObj);
            }

            _notyfService.Error(category.Message);
            return View();
        }
    }
}

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Controllers/ProductController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShoppingWebApplication.Service.Services;
using OnlineShoppingWebApplication.Service.Services.DTOs;
using OnlineShoppingWebApplication.ViewModels.Paging.Product;
using System;
using System.Threading.Tasks;

namespace OnlineShoppingWebApplication.WebApp.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly INotyfService _notyfService; 
        public ProductController(IProductService productService, ICategoryService categoryService, INotyfService notyfService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _notyfService = notyfService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 3)
        {
            ViewBag.Keyword = keyword;

            var request = new GetProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };

            var products = await _productService.GetProductsPaging(request);
            return View(products.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await _categoryService.GetAll();
            ViewBag.CategoryList = categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _categoryService.GetAll();
                ViewBag.CategoryList = categories;
                return View(dto);
            }
            var result = await _productService.Create(dto);
            if (result.IsSuccessed)
            {
                _notyfService.Success(result.Message);
                return RedirectToAction("Index");
            }

            _notyfService.Error(result.Message);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var product = await _productService.GetById(id);
            var categories = await _categoryService.GetAll();
            ViewBag.CategoryList = categories;

            if (product.IsSuccessed)
            {
                return View(product.ResultObj);
            }

            _notyfService.Error(product.Message);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductDto dto)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _categoryService.GetAll();
                ViewBag.CategoryList = categories;
                return View(dto);
            }

            var product = await _productService.Edit(dto);
            if (product.IsSuccessed)
            {
                _notyfService.Success(product.Message);
                return RedirectToAction("Index");
            }

            _notyfService.Error(product.Message);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _productService.DeleteById(id);
            if (result.IsSuccessed)
            {
                _notyfService.Success(result.Message);
            }
            else
            {
                _notyfService.Error(result.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var product = await _productService.GetIncludeCategoryById(id);

            if (product.IsSuccessed)
            {
                return View(product.ResultObj);
            }

            _notyfService.Error(product.Message);
            return View();
        }
    }
}

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Shared/_ConfirmDeletePartial.cshtml
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
   <form asp-action="Delete" asp-controller="Category">
       <input name="id" value="" hidden />
    <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="content-cofirm"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Delete</button>
      </div>
    </div>
  </div>
  </form>
</div>

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using OnlineShoppingWebApplication.Core.Entities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShoppingWebApplication.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
     <div class="container-fluid">
        <div class="row">
            <div class="col-2 sidenav-col">
                <div class="sidenav">
                    <div class="logo-container">
                        <button onclick="toggleSidenav()" class="logo">S</button>
                        <div class="logo-text">Shoppi</div>
                        <button class="btn-close" onclick="closeSidenav()">
                            <i class="close-icon fal fa-times"></i>
                        </button>
                    </div>
                    <div class="scrollwrap scrollwrap-delayed">
                        <ul class="sidenav-nav">
                            <li class="sidenav-nav-item">
                                <a class="sidenav-nav-link" asp-area="" asp-controller="Category" asp-action="Index">
                                    <i class="sidenav-link-icon fal fa-list-alt"></i>
                                    <span class="sidenav-link-text">Category</span>
                                </a>
                            </li>
                            <li class="sidenav-nav-item">
                                <a class="sidenav-nav-link" asp-area="" asp-controller="Product" asp-action="Index">
                                    <i class="sidenav-link-icon fal fa-box-open"></i>
                                    <span class="sidenav-link-text">Product</span>
                                </a>
                            </li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="sidenav-nav-item">
                                    <a class="sidenav-nav-link" asp-area="" asp-controller="User" asp-action="Index">
                                        <i class="sidenav-link-icon fal fa-user"></i>
                                        <span class="sidenav-link-text">User</span>
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-10 sidenav-main sidenav-content">
                <div class="row head">
                    <div class="head-content">
                        <div class="col-6 head-content-left">
                            <div class="search-container">
                                <div class="normal-search">
                                    <input type="text" class="search" placeholder="Search...">
                                    <i class="far fa-search search-icon"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-6 head-content-right">
                            <div class="head-menu">
                                <div class="head-menu-item">
                                    <button class="head-menu-item-btn ripple">
                                        <i class="far fa-bell menu-icon"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="head-user-avatar-container">
                                <div class="btn-group">
                                  <button type="button" class="btn btn-padding-unset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <div class="head-user-avatar">
                                        <img src="~/img/user3.png" alt="user" class="user-avatar">
                                        <div class="circle-indicator pulse"></div>
                                    </div>
                                  </button>
                                  <div class="dropdown-menu dropdown-menu-right">
                                    <button class="dropdown-item" type="button" onclick="window.location='@Url.Action("AccountInformation", "User")'"><i class="fal fa-user"></i> My Account</button>
                                    <button class="dropdown-item" type="button" onclick="window.location='@Url.Action("ChangePassword", "User")'"><i class="fal fa-key"></i> Change Password</button>
                                    <button class="dropdown-item" type="button" onclick="window.location='@Url.Action("LogOut", "User")'">
                                        <i class="fal fa-sign-out"></i> Sign Out
                                    </button>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="content-main">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("_ConfirmDeletePartial")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShoppingWebApplication.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/user.css" />
</head>
<body>
    <div class="wrapper">
      <div class="wrapped-div">
          <div class="tab-header">
              <a id="tab-link-signin" class="tab-link" asp-action="SignIn" asp-controller="User"><h2 id="tab-link-text-signin" class="tab-link-text">Sign In</h2></a>
              <a id="tab-link-signup" class="tab-link" asp-action="SignUp" asp-controller="User"><h2 id="tab-link-text-signup" class="tab-link-text">Sign Up</h2></a>
          </div>
          <div class="row">
              <div class="col-md-10 offset-md-1">
                    @RenderBody()
              </div>   
          </div>
      </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/user.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>