OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShoppingWebApplication.ViewModels.Paging;
using System.Threading.Tasks;

namespace OnlineShoppingWebApplication.WebApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Controllers/ProductController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShoppingWebApplication.Service.Services;
using OnlineShoppingWebApplication.Service.Services.DTOs;
using OnlineShoppingWebApplication.ViewModels.Paging.Product;
using System;
using System.Threading.Tasks;

namespace OnlineShoppingWebApplication.WebApp.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly INotyfService _notyfService; 
        public ProductController(IProductService productService, ICategoryService categoryService, INotyfService notyfService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _notyfService = notyfService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 3)
        {
            ViewBag.Keyword = keyword;

            var request = new GetProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };

            var products = await _productService.GetProductsPaging(request);
            return View(products.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await _categoryService.GetAll();
            ViewBag.CategoryList = categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _categoryService.GetAll();
                ViewBag.CategoryList = categories;
                return View(dto);
            }
            var result = await _productService.Create(dto);
            if (result.IsSuccessed)
            {
                _notyfService.Success(result.Message);
                return RedirectToAction("Index");
            }

            _notyfService.Error(result.Message);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var product = await _productService.GetById(id);
            var categories = await _categoryService.GetAll();
            ViewBag.CategoryList = categories;

            if (product.IsSuccessed)
            {
                return View(product.ResultObj);
            }

            _notyfService.Error(product.Message);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductDto dto)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _categoryService.GetAll();
                ViewBag.CategoryList = categories;
                return View(dto);
            }

            var product = await _productService.Edit(dto);
            if (product.IsSuccessed)
            {
                _notyfService.Success(product.Message);
                return RedirectToAction("Index");
            }

            _notyfService.Error(product.Message);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _productService.DeleteById(id);
            if (result.IsSuccessed)
            {
                _notyfService.Success(result.Message);
            }
            else
            {
                _notyfService.Error(result.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var product = await _productService.GetIncludeCategoryById(id);

            if (product.IsSuccessed)
            {
                return View(product.ResultObj);
            }

            _notyfService.Error(product.Message);
            return View();
        }
    }
}

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Product/Create.cshtml
@using OnlineShoppingWebApplication.Service.Services.DTOs

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ProductCreateDto

<h2>Create</h2>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create Product</li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("Index", "Product")'">
        <i class="fal fa-hand-o-left"></i> Back
    </button>
  </div>
  <div class="card-body">
    <form class="p-3" asp-controller="Product" asp-action="Create" method="post">
    <div class="form-group">
        <label for="categoryid" class="font-weight-bold">Category select</label>
        <select class="form-control" id="categoryid" asp-for="CategoryId">
          <option value="" selected>Choose...</option>
            @foreach (var item in ViewBag.CategoryList)
            {
                <option value="@item.Id">@item.Name</option>
           }
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="name" class="font-weight-bold">Name</label>
        <input type="text" class="form-control" id="name" asp-for="Name" placeholder="Enter name">
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="price" class="font-weight-bold">Price</label>
        <input type="number" class="form-control" id="name" asp-for="Price" placeholder="Enter price">
        <span asp-validation-for="Price" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="description" class="font-weight-bold">Description</label>
        <textarea rows="3" class="form-control" id="description" asp-for="Description" placeholder="Enter description"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
</div>

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Product/Details.cshtml
@using OnlineShoppingWebApplication.Service.Services.DTOs

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ProductDto

<h2>Details</h2>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Details Product</li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("Index", "Product")'">
        <i class="fal fa-hand-o-left"></i> Back
    </button>
  </div>
  <div class="card-body">
    <div class="p-3">
        <input hidden value="@Model.Id" />
      <div class="form-group">
        <label for="categoryid" class="font-weight-bold">Category</label>
        <input type="text" class="form-control" id="categoryid" asp-for="Category.Name" readonly>
      </div>
      <div class="form-group">
        <label for="name" class="font-weight-bold">Name</label>
        <input type="text" class="form-control" id="name" asp-for="Name" readonly>
      </div>
      <div class="form-group">
        <label for="price" class="font-weight-bold">Price</label>
        <input type="number" class="form-control" id="price" asp-for="Price" readonly>
    </div>
      <div class="form-group">
        <label for="description" class="font-weight-bold">Description</label>
        <textarea rows="3" class="form-control" id="description" asp-for="Description" readonly placeholder="Enter description"></textarea>
      </div>
    </div>
  </div>
</div>

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Product/Edit.cshtml
@using OnlineShoppingWebApplication.Service.Services.DTOs

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ProductDto

<h2>Edit</h2>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Product</li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("Index", "Product")'">
        <i class="fal fa-hand-o-left"></i> Back
    </button>
  </div>
  <div class="card-body">
    <form class="p-3" asp-controller="Product" asp-action="Edit" method="post">
        <input hidden value="@Model.Id" />
        <div class="form-group">
        <label for="categoryid" class="font-weight-bold">Category select</label>
        <select class="form-control" id="categoryid" asp-for="CategoryId">
            <option value="">Choose...</option>
            @foreach (var item in ViewBag.CategoryList)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="name" class="font-weight-bold">Name</label>
        <input type="text" class="form-control" id="name" asp-for="Name" placeholder="Enter name">
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="price" class="font-weight-bold">Price</label>
        <input type="number" class="form-control" id="name" asp-for="Price" placeholder="Enter price">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
      <div class="form-group">
        <label for="description" class="font-weight-bold">Description</label>
        <textarea rows="3" class="form-control" id="description" asp-for="Description" placeholder="Enter description"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
</div>

OnlineShoppingWebApplication/OnlineShoppingWebApplication.WebApp/Views/Product/Index.cshtml
@using OnlineShoppingWebApplication.ViewModels.Paging
@using OnlineShoppingWebApplication.Service.Services.DTOs
@model PagedResult<ProductDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Product</h2>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Product List</li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
      <div class="row">
          <div class="col-3">
              <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("Create", "Product")'">
                <i class="fal fa-plus-square"></i> Create
              </button>
          </div>
          <div class="col-9">
              <form asp-action="Index" method="get">
                    <div class="row">
                        <div class="col-9">
                            <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                        </div>
                        <div class="cold-3">
                            <button type="submit" class="btn btn-primary">Search</button>
                            <button type="button" onclick="window.location='@Url.Action("Index", "Product")'" class="btn btn-dark">Reset</button>
                        </div>
                    </div>
              </form>
          </div>
      </div>
    
  </div>
  <div class="card-body">
    @{
    int i = 0;
    <div class="table-responsive">
            <table class="table table-bordered table-striped" id="product">
                <thead class="thead-light">
                    <tr>
                        <th scope="col" class="w-10">#</th>
                        <th scope="col" class="w-20">Name</th>
                        <th scope="col" class="w-20">Price</th>
                        <th scope="col" class="w-30">Description</th>
                        <th scope="col" class="w-20">Action</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.Items)
            {
                i+=1;
                    <tr>
                        <th class="w-10" scope="row">@i</th>
                        <td class="w-20" id="name">@item.Name</td>
                        <td class="w-20" id="name">@item.Price</td>
                        <td class="w-30">@item.Description</td>
                        <td class="w-20">
                            <button type="button" class="btn btn-warning" onclick="window.location='@Url.Action("Details", "Product", new { id = @item.Id})'">
                                <i class="fal fa-eye"></i>
                            </button>
                            <button type="button" class="btn btn-info" onclick="window.location='@Url.Action("Edit", "Product", new { id = @item.Id})'">
                                <i class="fal fa-edit"></i>
                            </button>
                            <button value="@item.Id" type="button" class="btn btn-danger" id="btnDelete">
                                <i class="fal fa-trash-alt"></i>
                            </button>
                        </td>
                    </tr>
            }               
                </tbody>
            </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
}
  </div>
</div>